name: CI
on: 
  push:
    branches:
      - '**'        # matches every branch
      - '!master'
    tags:
      - '**'        # matches every tag
jobs:
  build:
    env:
      VCPKG_BINARY_SOURCES: clear;x-gha,readwrite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - run: pip install PyYAML requests
      - run: sudo apt install libwayland-dev libxkbcommon-dev wayland-protocols extra-cmake-modules xorg-dev
      - name: cmake configure
        run: |
          export CMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
          cmake -B build -S .
      - name: cmake build
        run: cmake --build build --config Release
